server:
  port: 8082
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/MVC1
    username: root
    password: 123
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true